### ISSUE TITLE
replace 1GC 'Mission' figure

### ISSUE THREAD

**Issue by mk618** [OneGeochemistry/OneGeochemistry.github.io#5]
https://onegeochemistry.github.io/our_mission.html#starting-onegeochemistry

urgently need to replace this figure with the one we made for the Elements article

**Comment by luciaprofeta** [comment]
![Elements_Fig1_ss_Prent_et_al](https://github.com/OneGeochemistry/OneGeochemistry.github.io/assets/54799767/4b1e952b-b32b-48f9-a77c-4d65982cba35)
I think this was the last version for the figure

**Comment by Hezel2000** [comment]
I replaced the previous figure with this new one.

**Comment by Hezel2000** [comment]
I replaced the previous figure with this new one.
